apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: fastapi-skaffold-debug
build:
  artifacts:
    - image: kludex/fastapi-simple-app
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - app.yml
